# Generated by Django 3.0.5 on 2020-04-24 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_libros'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='autor',
            name='prueba',
            field=models.CharField(default='prueba', max_length=80, verbose_name='Prueba'),
        ),
    ]
