# Generated by Django 3.0.5 on 2020-04-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_auto_20200423_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='prueba',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Prueba'),
        ),
    ]
