# Generated by Django 3.0.5 on 2020-04-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_auto_20200423_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='prueba',
            field=models.CharField(blank=True, default=models.CharField(max_length=80, verbose_name='Nombre'), max_length=80, null=True, verbose_name='Prueba'),
        ),
    ]
