# Generated by Django 3.0.5 on 2020-04-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Pedidos', '0002_auto_20200417_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(max_length=12),
        ),
    ]
