# Generated by Django 3.0.5 on 2020-04-23 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion_Pedidos', '0010_auto_20200423_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='articulos',
        ),
    ]
